# Generated by Django 4.2 on 2025-02-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0004_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
